import type { Metadata } from 'next'
import { Inter, Special_Elite, Roboto } from 'next/font/google'
import '../globals.css'

const inter = Inter({ subsets: ['latin'] })
const roboto= Roboto({weight:'400', subsets:['latin']})
const special_elite = Special_Elite({weight:"400", subsets:['latin'], variable:"--office-font"})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={`${inter.className} ${special_elite.variable}`}>{children}</body>
    </html>
  )
}
